### ISSUE TITLE
Publish maildocker-php to Packagist

### ISSUE THREAD

**Issue by jspetrak** [maildocker/maildocker-php#1]
Thought composer.json is present in the project, the bundle is not available at packagist.org and can't be fetched to projects.

**Comment by jairojair** [comment]
:+1:

**Comment by ssjunior** [comment]
Hi @jspetrak @jairojair 

Thank you for the feedback. We will publish it to Packagist in the next days. If you need something else, please let me know.

**Comment by jspetrak** [comment]
@ssjunior Thanks! I keep watching the issue&repo. For time being, there is a workaround, I have used in mine composer.json:

`
    "require": {
        "maildocker/maildocker": "dev-master",
    },
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/maildocker/maildocker-php"
        }
    ]`

**Comment by danielkohn** [comment]
Thank @jspetrak! I'll commit the changes here.
